export const studyFlashcardTokens = {
  container: 'w-full overflow-hidden rounded-[24px] bg-surface-container-lowest',
  idleContainer: 'border border-surface-variant shadow-study-flashcard',
  knownContainer: 'border-2 border-secondary-container shadow-study-flashcard-selected',
  unknownContainer: 'border-2 border-surface-variant shadow-study-flashcard-muted',
  disabledContainer: 'opacity-70',
  selectionIndicator: 'absolute right-4 top-4 z-10 items-center justify-center',
  content: 'min-w-0 px-10 pt-10',
  contentDefaultBottom: 'pb-10',
  contentSelectedBottom: 'pb-8',
  contentStack: 'min-w-0 gap-6',
  metaRow: 'min-w-0 flex-row items-start justify-between gap-4',
  metaGrow: 'min-w-0 flex-1',
  categoryPill:
    'self-start rounded-full bg-secondary-container px-3 py-1.5 text-[12px] font-medium uppercase tracking-[1.4px] leading-[12px] text-study-on-surface-variant',
  categoryPillUnknown: 'bg-surface-variant',
  moreButton: 'h-9 w-9 items-center justify-center rounded-full active:scale-90 active:bg-surface-container-low',
  textBlock: 'min-w-0 gap-2',
  title: 'text-[24px] font-bold leading-[31.2px] text-study-on-surface',
  question: 'mt-2 text-[18px] leading-[28.8px] text-study-on-surface-variant',
  tipBox: 'mt-4 rounded-xl border border-surface-variant bg-surface-container-low p-4',
  tipText: 'text-[16px] italic leading-[25.6px] text-study-on-surface-variant',
  explanationBox:
    'relative mt-4 overflow-hidden rounded-xl border border-surface-variant bg-study-surface px-6 py-6',
  explanationEdge: 'absolute inset-y-0 left-0 w-1 bg-study-primary opacity-20',
  explanationStack: 'gap-4',
  explanationTitle: 'text-[14px] font-bold uppercase tracking-[1.2px] leading-[14px] text-study-primary',
  explanationParagraph: 'text-[16px] leading-[25.6px] text-study-on-surface-variant',
  explanationListRow: 'flex-row items-start gap-2',
  explanationBullet: 'pt-1 text-[16px] leading-[25.6px] text-study-on-surface-variant',
  explanationAnswer:
    'mt-2 self-start rounded border border-secondary-container bg-secondary-container/30 px-3 py-2',
  explanationAnswerText: 'text-[14px] font-bold leading-[14px] text-study-primary',
  flipArea: 'min-h-[72px] border-t border-surface-variant',
  flipButton: 'min-h-[72px] items-center justify-center gap-1.5 px-6 py-4 active:bg-surface-container-low',
  flipButtonDisabled: 'opacity-50',
  flipLabel: 'text-[12px] font-medium uppercase tracking-[1.6px] leading-[12px] text-outline',
  actionBar: 'min-h-[72px] flex-row border-t border-surface-variant bg-surface-container-lowest',
  actionButton:
    'min-h-[72px] flex-1 flex-row items-center justify-center gap-2 px-4 py-4 active:scale-[0.99] active:opacity-95',
  actionButtonDisabled: 'active:scale-100 active:opacity-100',
  actionDivider: 'border-r border-surface-variant',
  actionLabel: 'text-[14px] font-bold uppercase tracking-[1px] leading-[14px]',
  actionKnownIdle: 'text-study-primary',
  actionUnknownIdle: 'text-outline',
  actionKnownSelected: 'bg-surface-container text-study-primary',
  actionUnknownSelected: 'bg-surface-variant text-study-on-surface-variant',
  actionMuted: 'opacity-60',
} as const

export const studyFlashcardColorTokens = {
  more: '#6D7B6D',
  selectedIndicator: '#006D36',
  studyPrimary: '#006D36',
  outline: '#6D7B6D',
  onSurfaceVariant: '#3D4A3E',
} as const
